Cognifide.PowerShell/Core/Provider/PsSitecoreItemProvider.DynamicParameters.cs
Cognifide.PowerShell/Core/Provider/PsSitecoreItemProvider.PathHandling.cs
Cognifide.PowerShell/Core/Provider/PsSitecoreItemProvider.cs

#444 Get-ChildItem support for ID parameter

---

Cognifide.PowerShell/Commandlets/Data/GetItemReferenceCommand.cs

Implementation fix for issue #455

Issue #455

---

Cognifide.PowerShell/Commandlets/Presentation/RemoveRenderingCommand.cs

Issue #452 - Renderings processed in reverse to avoid exception, and added proper
error if no rendering found (previous code was resulting in an exception
due to the `Aggregate` call).

Fixes for Remove-Rendering

---

Cognifide.PowerShell/Cognifide.PowerShell.csproj
Cognifide.PowerShell/Commandlets/Data/ResetItemFieldCommand.cs
Cognifide.PowerShell/Commandlets/Presentation/ResetLayoutCommand.cs
Documentation/Get-ItemField.ps1
Documentation/Get-Layout.ps1
Documentation/Reset-ItemField.ps1
Documentation/Reset-Layout.ps1
Documentation/Set-Layout.ps1

Added new commands Reset-ItemField and Reset-Layout. Can follow this with update to documentation.

Added new commands for resetting fields + layouts.

---

Cognifide.PowerShell/Data/serialization/master/sitecore/system/Modules/PowerShell/Script Library/Platform/Internal/Integrations/Content Editor Gutter.item
Cognifide.PowerShell/Data/serialization/master/sitecore/system/Modules/PowerShell/Script Library/Platform/Internal/Integrations/Content Editor Ribbon.item

Fix for issue #480, so that the errors raised in normal use of the script are swalloed.

Silent error handling in integration scripts

---

Cognifide.PowerShell/Cognifide.PowerShell.csproj
Cognifide.PowerShell/Commandlets/Data/AddBaseTemplateCommand.cs
Cognifide.PowerShell/Commandlets/Data/BaseTemplateItemCommand.cs
Cognifide.PowerShell/Commandlets/Data/RemoveBaseTemplateCommand.cs
Cognifide.PowerShell/Commandlets/Data/SetItemTemplateCommand.cs
Cognifide.PowerShell/Core/Utility/PathUtilities.cs
Documentation/Add-BaseTemplate.ps1
Documentation/Get-ItemTemplate.ps1
Documentation/Remove-BaseTemplate.ps1
Documentation/Set-ItemTemplate.ps1

Merging new cmdlets from fork.

---

Cognifide.PowerShell/Client/Applications/ExecutionMessages.cs
Cognifide.PowerShell/Client/Applications/PowerShellIse.cs
Cognifide.PowerShell/sitecore modules/PowerShell/Scripts/SpeShared.js
Cognifide.PowerShell/sitecore modules/PowerShell/Scripts/console.js

Implementation of #613 
How it looks:

#613 Prevent window close when script is running

---

Cognifide.PowerShell/sitecore modules/PowerShell/Services/RemoteScriptCall.ashx.cs

#774 RemoteScriptCall "handle" service / no context DB

---

Cognifide.PowerShell/sitecore modules/PowerShell/Scripts/ise.js

Instead of lowering `updateRibbon` function interval we can add "event handler" to the `onPaste` event.

#794 | Update ribbon on paste in standalone PowerShellIse

---

Cognifide.PowerShell.Sitecore8/sitecore modules/PowerShell/Styles/ise.css
Cognifide.PowerShell/sitecore modules/PowerShell/Scripts/ise.js

#907 | ISE UX/UI improvements

---

Cognifide.PowerShell/Client/Commands/MenuItems/ExecutePowerShellScript.cs

Problem with ability to pass messages from script to the executing Content Editor window upon script end

---

Cognifide.PowerShell/Integrations/Tasks/ScriptedItemEventHandler.cs

Address the performance penalty associated with script
session creation (varies by machine, anywhere from 20ms-150ms with some
quick testing). This penalty can be extremely noticeable under certain
scenarios that fire off a substational amount of item events (i.e.,
republishing). Instead of creating the script session and then
evaluating a collection of scripts one at a time, the OnEvent() function
will now run through all integration scripts associated with the current
event and perform checks to ensure the scripts will be run and require a session to do so.
* Move script conditions outside of session creation body.
* Set global context options outside of individual script execution
loop.

Delay script session creation unless needed

---

Cognifide.PowerShell/Commandlets/Data/AddItemVersionCommand.cs

Updating AddItemVersionCommands to process fields by ID instead of name.

---

Cognifide.PowerShell/Data/Serialization/Scripts/Script Library/Script Library/SPE - Reporting/Content Reports/Reports/Content Audit/Items have no publishable vers.yml

Added logic in authoring report script to check if the item is marked as unpublishable or not.

Added check for Unpublishable Item

---

Cognifide.PowerShell/Client/Applications/PowerShellResultViewerList.cs

Fixes #1051
Related to: #789 
Tested in:
- ISE
- CE
- EE

#1051 | MissingDataIcon not working

---

Cognifide.PowerShell/Client/Commands/MenuItems/ScriptLibraryMenuItem.cs

#1047 | Powershell Toolbox - entries order

---

Cognifide.PowerShell/sitecore modules/PowerShell/Scripts/ise.js

#1065 | Redundant requests to the server

---

Cognifide.PowerShell/Cognifide.PowerShell.csproj
Cognifide.PowerShell/Commandlets/Presentation/AddPlaceholderSettingCommand.cs
Cognifide.PowerShell/Commandlets/Presentation/NewPlaceHolderSettingCommand.cs

I have implemented a couple of cmdlets to allow adding placeholder settings to presentation details.
I tried to implement them following other similar commands.
It's my first pull request here, so let me know anything I'm missing

#949 Add placeholder 

---

src/Spe/sitecore modules/PowerShell/Scripts/VariablePrompt.js
src/Spe/sitecore modules/Shell/PowerShell/PowerShellMultiValuePrompt.xml

Adding logic to detect textarea, and not submit the form
Moving embedded script to external file #formatting #4thgradecoder

Enter fires a keypress

---

.gitignore
cli/.config/dotnet-tools.json
cli/.gitignore
cli/.sitecore/schemas/ModuleFile.schema.json
cli/.sitecore/schemas/RootConfigurationFile.schema.json
cli/.sitecore/schemas/UserConfiguration.schema.json
cli/README.md
cli/modules/Spe.Core.module.json
cli/modules/Spe.Rules.module.json
cli/modules/Spe.Scripts.module.json
cli/modules/Spe.UI.module.json
cli/sitecore.json
src/Spe/App_Config/Include/Spe/Spe.Serialization.config
unicorn/SPE/UI/Start Menu Console/PowerShell Console.yml
unicorn/SPE/UI/Start Menu ISE/PowerShell ISE.yml

This PR contains all the necessary files/changes to generate resource files for SPE
- correct serialization data
- plugins/cli configuraion
- SPE modules definitions (for serialization)
- README with info how to use this integration

Items as resources support

---

src/Spe/Core/Settings/PredefinedVariables.cs

#1274 | Backward compatibility for obsolete variables

---

src/Spe/Core/Settings/Authorization/SessionElevationManager.cs

https://github.com/SitecorePowerShell/Console/issues/1297

Allow case insensitive parsing of elevation

---

src/Spe/App_Config/Include/Spe/Spe.Serialization.config
unicorn/SPE/Scripts/SPE/SPE/Core/Platform/Internal/ISE Plugins/Scripts containing.yml

Fix for #1327 : ISE Plugin "Scripts Containing" does not work most of the time

#1327 : ISE Plugin "Scripts Containing" does not work most of the time

---

unicorn/SPE/Scripts/SPE/SPE/Core/Platform/Internal/Integrations/Content Editor Ribbon.yml

Issue in creating multiple custom ribbon elements #1355

Issue in creating multiple custom ribbon elements
